from enum import Enum

class AllureTag(str, Enum):
    SMOKE = "SMOKE"
    REGRESSION = "REGRESSION"
    NEGATIVE = "NEGATIVE"
    AUTH = "AUTH"
    USERS = "USERS"
    FILES = "FILES"
    COURSES = "COURSES"
    EXERCISES = "EXERCISES"

    GET_ENTITY = "GET_ENTITY"
    GET_ENTITIES = "GET_ENTITIES"
    CREATE_ENTITY = "CREATE_ENTITY"
    UPDATE_ENTITY = "UPDATE_ENTITY"
    DELETE_ENTITY = "DELETE_ENTITY"
    VALIDATE_ENTITY = "VALIDATE_ENTITY"